package edu.winona.cs.app;

import edu.winona.cs.gamelogic.AdjacencyListMaker;
import edu.winona.cs.gamelogic.DifficultyLevel;
import edu.winona.cs.gamelogic.MoveLogic;
import edu.winona.cs.gamelogic.Space;
import edu.winona.cs.image.ImageProcessor;
import edu.winona.cs.temp.Cell;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

import javax.swing.JFileChooser;

/**
 * This is the main game screen. - This is where users play the sliding game
 *
 * @author Erika Tix
 */
public class GameScreenEasy extends javax.swing.JFrame {

    private static final long serialVersionUID = 8287565246570842716L;

    //move logic
    MoveLogic move = new MoveLogic();

    //image/game processing
    List<BufferedImage> imageList = new ArrayList<>();
    ImageProcessor image = new ImageProcessor();
    AdjacencyListMaker adjacency = new AdjacencyListMaker();
    List<Space> spaces = new ArrayList();

    //flag for determining if first button clicked
    //if first, save button number
    //if second, call the move method
    //then reset
    Boolean isFirstButton = true;
    Space firstSpace; //also the moveFrom space

    /**
     * Creates new form GameScreenEasy
     */
    public GameScreenEasy() {
        try {
            initComponents();

            for (int i = 1; i < 5; i++) {
                //create space
                Space tempSpace = new Space(i);
                //assign its adjacency list
                tempSpace.setAdjacencyList(adjacency.makeEasyAdjacencyList(tempSpace));
                //add to spaces list
                spaces.add(tempSpace);
            }

            //filechooser
            JFileChooser jfc = new JFileChooser(new File("."));
            //int returnVal = -1;
            int returnVal = jfc.showOpenDialog(this);
            while (returnVal != JFileChooser.APPROVE_OPTION) {
                jfc.showOpenDialog(null);
            }

            //get file
            File file = jfc.getSelectedFile();

            //assign file
            image.assignImage(file);

            //divide image
            imageList = image.divideImage(4);

            //TODO assign an empty button
            //assign divide images to buttons
            button1.setIcon(new ImageIcon(imageList.get(0)));
            button2.setIcon(new ImageIcon(imageList.get(1)));
            button3.setIcon(new ImageIcon(imageList.get(2)));
            button4.setIcon(new ImageIcon(imageList.get(3)));

        } catch (IOException ex) {
            Logger.getLogger(GameScreenEasy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setMaximumSize(new java.awt.Dimension(25, 25));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setMaximumSize(new java.awt.Dimension(25, 25));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setMaximumSize(new java.awt.Dimension(25, 25));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button1)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:

        //check if first click
        if (isFirstButton) {
            //remember button
            firstSpace = spaces.get(1);
        } else {
            //swap
            move.move(imageList, firstSpace, spaces.get(1));
            //reset button flag
            isFirstButton = false;
            //update images
            reassignImages();
        }

    }//GEN-LAST:event_button4ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:

        //check if first click
        if (isFirstButton) {
            //remember button
            firstSpace = spaces.get(2);
        } else {
            //swap
            move.move(imageList, firstSpace, spaces.get(2));
            //reset button flag
            isFirstButton = false;
            //update images
            reassignImages();
        }

    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:

        //check if first click
        if (isFirstButton) {
            //remember button
            firstSpace = spaces.get(3);
        } else {
            //swap
            move.move(imageList, firstSpace, spaces.get(3));
            //reset button flag
            isFirstButton = false;
            //update images
            reassignImages();
        }

    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:

        //check if first click
        if (isFirstButton) {
            //remember button
            firstSpace = spaces.get(0);
        } else {
            //swap
            move.move(imageList, firstSpace, spaces.get(0));
            //reset button flag
            isFirstButton = false;
            //update images
            reassignImages();
        }

    }//GEN-LAST:event_button1ActionPerformed

    //TODO fix this so it can include the missing space
    public void reassignImages() {
        //assign divide images to buttons
        button1.setIcon(new ImageIcon(imageList.get(0)));
        button2.setIcon(new ImageIcon(imageList.get(1)));
        button3.setIcon(new ImageIcon(imageList.get(2)));
        button4.setIcon(new ImageIcon(imageList.get(3)));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreenEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreenEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreenEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreenEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreenEasy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JFrame jFrame1;
    // End of variables declaration//GEN-END:variables

}
